import { DataTypes } from 'sequelize';
import sequelize from '../db/db.js';

const Listing = sequelize.define('Listing', {
  title: DataTypes.STRING,
  lat: DataTypes.FLOAT,
  lng: DataTypes.FLOAT,
  image: DataTypes.STRING,
  price: DataTypes.INTEGER,
  rating: DataTypes.FLOAT,
  reviews: DataTypes.INTEGER,
  amenities: DataTypes.ARRAY(DataTypes.STRING),
  description: DataTypes.TEXT,
  isAvailable: DataTypes.BOOLEAN,
});

export default Listing;




export const mocklistings = [
  {
    id: 1,
    title: "Cozy 2BHK near Downtown",
    lat: 40.748817,
    lng: -73.985428,
    image: "https://via.placeholder.com/150",
    price: 1000,
    rating: 4.5,
    reviews: 100,
    amenities: ["Wifi", "Parking", "Pool"],
    description: "Cozy 2BHK with a private balcony near Midtown.",
    isAvailable: true,
  },
  {
    id: 2,
    title: "Studio apartment near Central Park",
    lat: 40.785091,
    lng: -73.968285,
    image: "https://via.placeholder.com/150",
    price: 800,
    rating: 4.2,
    reviews: 75,
    amenities: ["Wifi", "Parking", "Gym"],
    description: "Studio with gym access steps from Central Park.",
    isAvailable: true,
  },
  {
    id: 3,
    title: "1BR Loft in SoHo",
    lat: 40.724545,
    lng: -74.000708,
    image: "https://via.placeholder.com/150",
    price: 1300,
    rating: 4.7,
    reviews: 220,
    amenities: ["Wifi", "Washer", "Dryer"],
    description: "Stylish loft with exposed brick in SoHo.",
    isAvailable: true,
  },
  {
    id: 4,
    title: "Bright 2BR near Brooklyn Bridge",
    lat: 40.706086,
    lng: -73.996864,
    image: "https://via.placeholder.com/150",
    price: 950,
    rating: 4.3,
    reviews: 150,
    amenities: ["Wifi", "Kitchen", "Air Conditioning"],
    description: "Sunny apartment with views near Brooklyn Bridge.",
    isAvailable: true,
  },
  {
    id: 5,
    title: "Modern Flat near Times Square",
    lat: 40.758896,
    lng: -73.985130,
    image: "https://via.placeholder.com/150",
    price: 1100,
    rating: 4.6,
    reviews: 198,
    amenities: ["Wifi", "Smart TV", "Elevator"],
    description: "Steps away from Broadway shows and Times Square.",
    isAvailable: true,
  },
  {
    id: 6,
    title: "Greenpoint Garden Studio",
    lat: 40.730465,
    lng: -73.954865,
    image: "https://via.placeholder.com/150",
    price: 750,
    rating: 4.1,
    reviews: 90,
    amenities: ["Garden", "Wifi", "Pet Friendly"],
    description: "Charming studio with backyard access in Brooklyn.",
    isAvailable: true,
  },
  {
    id: 7,
    title: "Spacious 3BR in Astoria",
    lat: 40.764357,
    lng: -73.923462,
    image: "https://via.placeholder.com/150",
    price: 1200,
    rating: 4.4,
    reviews: 160,
    amenities: ["Parking", "Washer", "Kitchen"],
    description: "Great for families, close to Steinway Street.",
    isAvailable: true,
  },
  {
    id: 8,
    title: "Financial District High-Rise",
    lat: 40.707491,
    lng: -74.011276,
    image: "https://via.placeholder.com/150",
    price: 1400,
    rating: 4.8,
    reviews: 210,
    amenities: ["Wifi", "Doorman", "Gym"],
    description: "Luxury building in Manhattan's financial center.",
    isAvailable: true,
  },
  {
    id: 9,
    title: "Minimalist Apartment in Chelsea",
    lat: 40.746500,
    lng: -74.001374,
    image: "https://via.placeholder.com/150",
    price: 950,
    rating: 4.5,
    reviews: 130,
    amenities: ["Wifi", "Air Conditioning", "Balcony"],
    description: "Perfect for remote workers and creatives.",
    isAvailable: true,
  },
  {
    id: 10,
    title: "Luxury Penthouse in Upper East Side",
    lat: 40.773565,
    lng: -73.956555,
    image: "https://via.placeholder.com/150",
    price: 2000,
    rating: 4.9,
    reviews: 300,
    amenities: ["Hot Tub", "Terrace", "Concierge"],
    description: "Live luxuriously with views of the Met and Park.",
    isAvailable: true,
  },
  {
    id: 11,
    title: "Compact Room in Chinatown",
    lat: 40.715751,
    lng: -73.997031,
    image: "https://via.placeholder.com/150",
    price: 600,
    rating: 4.0,
    reviews: 65,
    amenities: ["Wifi", "Shared Bathroom", "Fan"],
    description: "Budget stay close to iconic Chinese eateries.",
    isAvailable: true,
  },
  {
    id: 12,
    title: "West Village Hideaway",
    lat: 40.734573,
    lng: -74.002742,
    image: "https://via.placeholder.com/150",
    price: 1050,
    rating: 4.6,
    reviews: 115,
    amenities: ["Wifi", "Bookshelf", "Kitchen"],
    description: "Quaint and peaceful spot in West Village.",
    isAvailable: true,
  },
  {
    id: 13,
    title: "Urban Retreat near Columbia University",
    lat: 40.807536,
    lng: -73.962573,
    image: "https://via.placeholder.com/150",
    price: 850,
    rating: 4.3,
    reviews: 84,
    amenities: ["Wifi", "Study Desk", "Heater"],
    description: "Ideal for students or remote work.",
    isAvailable: true,
  },
  {
    id: 14,
    title: "Hip Williamsburg Flat",
    lat: 40.708116,
    lng: -73.957070,
    image: "https://via.placeholder.com/150",
    price: 980,
    rating: 4.5,
    reviews: 150,
    amenities: ["Wifi", "Bike Rack", "AC"],
    description: "Trendy apartment near Bedford Ave.",
    isAvailable: true,
  },
  {
    id: 15,
    title: "Sunny Bronx Apartment",
    lat: 40.844782,
    lng: -73.864827,
    image: "https://via.placeholder.com/150",
    price: 700,
    rating: 4.1,
    reviews: 70,
    amenities: ["Wifi", "Parking", "Elevator"],
    description: "Affordable and bright Bronx living.",
    isAvailable: true,
  }
];


